services:
  redis:
    image: redis:7-alpine
    container_name: sentinel-redis
    command:
      - redis-server
      - --maxmemory-policy
      - noeviction
      - --maxmemory
      - 256mb
      - --appendonly
      - "no"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 2s
